# Generated by Django 3.1.7 on 2021-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gabinete', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('curso_id', models.IntegerField()),
                ('departamento_id', models.IntegerField()),
                ('faculdade_id', models.IntegerField()),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamentoid', models.IntegerField(db_column='DepartamentoID')),
                ('faculdadeid', models.IntegerField(db_column='FaculdadeID')),
            ],
            options={
                'db_table': 'coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professoruniversitario',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamento_id', models.IntegerField()),
                ('faculdade_id', models.IntegerField()),
            ],
            options={
                'db_table': 'professoruniversitario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
                ('inscricao_id', models.IntegerField()),
            ],
            options={
                'db_table': 'responsavel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=20)),
                ('valido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
    ]
