# Generated by Django 3.2 on 2021-04-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetManagement', '0001_initial'),
        ('FormManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventtype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'eventtype',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('wasvalidated', models.TextField(db_column='wasValidated')),
                ('eventname', models.CharField(db_column='eventName', max_length=255)),
                ('campusid', models.ForeignKey(db_column='CampusID', on_delete=django.db.models.deletion.DO_NOTHING, to='AssetManagement.campus')),
                ('eventtypeid', models.ForeignKey(db_column='EventTypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='PreEventManagement.eventtype')),
                ('formfeedbackid', models.ForeignKey(db_column='FormFeedBackID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Event2feedbackForm', to='FormManagement.form')),
                ('formresgistrationid', models.ForeignKey(db_column='FormResgistrationID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='Event2registerForm', to='FormManagement.form')),
                ('proponentid', models.ForeignKey(db_column='ProponentID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='AssetLogistics',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('seats', models.IntegerField(blank=True, db_column='Seats', null=True)),
                ('seatsforreducedmobility', models.IntegerField(blank=True, db_column='SeatsForReducedMobility', null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
                ('equipmenttypeid_equipmenttype', models.ForeignKey(blank=True, db_column='EquipmentTypeID_EquipmentType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AssetManagement.equipmenttype')),
                ('eventid_event', models.ForeignKey(db_column='EventID_Event', on_delete=django.db.models.deletion.DO_NOTHING, to='PreEventManagement.event')),
                ('servicetypeid_servicetype', models.ForeignKey(blank=True, db_column='ServiceTypeID_ServiceType', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='AssetManagement.servicetype')),
            ],
            options={
                'db_table': 'asset_logistics',
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('assetid_asset', models.ForeignKey(db_column='AssetID_Asset', on_delete=django.db.models.deletion.DO_NOTHING, to='AssetManagement.asset')),
                ('eventid_event', models.ForeignKey(db_column='EventID_Event', on_delete=django.db.models.deletion.DO_NOTHING, to='PreEventManagement.event')),
            ],
            options={
                'db_table': 'asset_event',
            },
        ),
    ]
