# Generated by Django 3.1.7 on 2021-04-23 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('assetname', models.CharField(db_column='AssetName', max_length=255, unique=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('buildingname', models.CharField(db_column='BuildingName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('campusname', models.CharField(db_column='CampusName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipmenttype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'equipmenttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'servicetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('assetid', models.OneToOneField(db_column='AssetID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='AssetManagement.asset')),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('assetid', models.OneToOneField(db_column='AssetID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='AssetManagement.asset')),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('assetid', models.OneToOneField(db_column='AssetID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='AssetManagement.asset')),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
