
# Generated by Django 3.2 on 2021-04-28 14:54


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
                ('dateofcreation', models.DateTimeField(db_column='DateOfCreation')),
            ],
            options={
                'db_table': 'answer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('formname', models.CharField(db_column='FormName', max_length=255)),
                ('dateofcreation', models.DateTimeField(db_column='DateOfCreation')),
                ('dateoflastedit', models.DateTimeField(db_column='DateOfLastEdit')),
                ('createdby', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.DO_NOTHING, related_name='FormCreatedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Formtype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'formtype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('dateofcreation', models.DateTimeField(db_column='DateOfCreation')),
                ('dateoflastedit', models.DateTimeField(db_column='DateOfLastEdit')),
                ('createdby', models.ForeignKey(db_column='CreatedBy', on_delete=django.db.models.deletion.DO_NOTHING, related_name='QuestionCreatedBy', to=settings.AUTH_USER_MODEL)),
                ('lasteditedby', models.ForeignKey(db_column='LastEditedBy', on_delete=django.db.models.deletion.DO_NOTHING, related_name='QuestionLastEditedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'questions',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'questiontype',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='QuestionsForm',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('formid_form', models.ForeignKey(db_column='FormID_Form', on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.form')),
                ('questionsid_questions', models.ForeignKey(db_column='QuestionsID_Questions', on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.questions')),
            ],
            options={
                'db_table': 'questions_form',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='questiontypeid_questiontype',
            field=models.ForeignKey(db_column='QuestionTypeID_QuestionType', on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.questiontype'),
        ),
        migrations.CreateModel(
            name='Multipleoptions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('option', models.CharField(db_column='Option', max_length=255)),
                ('questionsid_questions', models.ForeignKey(db_column='QuestionsID_Questions', on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.questions')),
            ],
            options={
                'db_table': 'multipleoptions',
                'managed': True,
            },
        ),
    ]
