# Generated by Django 3.1.7 on 2021-04-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('formname', models.CharField(db_column='FormName', max_length=255)),
                ('dateofcreation', models.DateTimeField(db_column='DateOfCreation')),
                ('dateoflastedit', models.DateTimeField(db_column='DateOfLastEdit')),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formtype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'formtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multipleoptions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('option', models.CharField(db_column='Option', max_length=255)),
            ],
            options={
                'db_table': 'multipleoptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionsForm',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'questions_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'questiontype',
                'managed': False,
            },
        ),
    ]
