# Generated by Django 3.2 on 2021-04-26 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Models', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('FormManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='eventtypeid',
            field=models.ForeignKey(db_column='EventTypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='Models.eventtype'),
        ),
        migrations.AddField(
            model_name='form',
            name='formtypeid_formtype',
            field=models.ForeignKey(db_column='FormTypeID_FormType', on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.formtype'),
        ),
        migrations.AddField(
            model_name='form',
            name='lasteditedby',
            field=models.ForeignKey(db_column='LastEditedBy', on_delete=django.db.models.deletion.DO_NOTHING, related_name='FormLastEditedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='eventid_event',
            field=models.ForeignKey(blank=True, db_column='EventID_Event', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Models.event'),
        ),
        migrations.AddField(
            model_name='answer',
            name='questionsid_questions',
            field=models.ForeignKey(db_column='QuestionsID_Questions', on_delete=django.db.models.deletion.DO_NOTHING, to='FormManagement.questions'),
        ),
        migrations.AddField(
            model_name='answer',
            name='resgistrationid',
            field=models.ForeignKey(blank=True, db_column='ResgistrationID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Models.resgistration'),
        ),
    ]
