# Generated by Django 3.2 on 2021-04-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormManagement', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='published',
            field=models.BinaryField(db_column='published', default=0),
        ),
    ]
