# Generated by Django 3.2 on 2021-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FormManagement', '0003_form_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='published',
            field=models.BooleanField(db_column='published', default=False),
        ),
    ]
