# Generated by Django 3.2 on 2021-04-28 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resgistration',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('waspresent', models.IntegerField(blank=True, db_column='WasPresent', null=True)),
            ],
            options={
                'db_table': 'resgistration',
            },
        ),
    ]
