# Generated by Django 3.2 on 2021-04-28 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PreEventManagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EventManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resgistration',
            name='eventid_event',
            field=models.ForeignKey(db_column='EventID_Event', on_delete=django.db.models.deletion.DO_NOTHING, to='PreEventManagement.event'),
        ),
        migrations.AddField(
            model_name='resgistration',
            name='participantuserid',
            field=models.ForeignKey(db_column='ParticipantUserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
