# Generated by Django 3.1.7 on 2021-04-13 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gabinete', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('answer', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'answer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('assetname', models.CharField(db_column='AssetName', max_length=255, unique=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'asset',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'asset_event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AssetLogistics',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('seats', models.IntegerField(blank=True, db_column='Seats', null=True)),
                ('seatsforreducedmobility', models.IntegerField(blank=True, db_column='SeatsForReducedMobility', null=True)),
                ('quantity', models.IntegerField(db_column='Quantity')),
            ],
            options={
                'db_table': 'asset_logistics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('buildingname', models.CharField(db_column='BuildingName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'building',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('campusname', models.CharField(db_column='CampusName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'campus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('curso_id', models.IntegerField()),
                ('departamento_id', models.IntegerField()),
                ('faculdade_id', models.IntegerField()),
            ],
            options={
                'db_table': 'colaborador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordenador',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamentoid', models.IntegerField(db_column='DepartamentoID')),
                ('faculdadeid', models.IntegerField(db_column='FaculdadeID')),
            ],
            options={
                'db_table': 'coordenador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('day', models.DateField(db_column='Day')),
            ],
            options={
                'db_table': 'day',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipmenttype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'equipmenttype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('wasvalidated', models.TextField(db_column='wasValidated')),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Eventtype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'eventtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Formtype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255)),
            ],
            options={
                'db_table': 'formtype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informacaomensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('pendente', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('lido', models.IntegerField()),
                ('emissorid', models.IntegerField(blank=True, null=True)),
                ('recetorid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'informacaomensagem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Informacaonotificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('pendente', models.IntegerField()),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('lido', models.IntegerField()),
                ('emissorid', models.IntegerField(blank=True, null=True)),
                ('recetorid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'informacaonotificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagemenviada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mensagemenviada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mensagemrecebida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem_id', models.IntegerField()),
            ],
            options={
                'db_table': 'mensagemrecebida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multipleoptions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('option', models.CharField(db_column='Option', max_length=255)),
            ],
            options={
                'db_table': 'multipleoptions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('unread', models.IntegerField()),
                ('actor_object_id', models.CharField(max_length=255)),
                ('verb', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('action_object_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField()),
                ('public', models.IntegerField()),
                ('deleted', models.IntegerField()),
                ('emailed', models.IntegerField()),
                ('data', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('action_object_content_type_id', models.IntegerField(blank=True, null=True)),
                ('actor_content_type_id', models.IntegerField()),
                ('recipient_id', models.IntegerField()),
                ('target_content_type_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacao',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Professoruniversitario',
            fields=[
                ('utilizador_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gabinete', models.CharField(db_column='Gabinete', max_length=255)),
                ('departamento_id', models.IntegerField()),
                ('faculdade_id', models.IntegerField()),
            ],
            options={
                'db_table': 'professoruniversitario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'questions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionsForm',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'questions_form',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Questiontype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.IntegerField(db_column='TypeName')),
            ],
            options={
                'db_table': 'questiontype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Resgistration',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('date', models.IntegerField(blank=True, db_column='Date', null=True)),
                ('waspresent', models.IntegerField(blank=True, db_column='WasPresent', null=True)),
            ],
            options={
                'db_table': 'resgistration',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Responsavel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=128)),
                ('tel', models.CharField(max_length=128)),
                ('inscricao_id', models.IntegerField()),
            ],
            options={
                'db_table': 'responsavel',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicetype',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('typename', models.CharField(db_column='TypeName', max_length=255, unique=True)),
            ],
            options={
                'db_table': 'servicetype',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Timebracket',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('starttime', models.TimeField(db_column='StartTime')),
                ('endtime', models.TimeField(db_column='EndTime')),
            ],
            options={
                'db_table': 'timebracket',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('user_ptr_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contacto', models.CharField(max_length=20)),
                ('valido', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'utilizador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('assetid', models.OneToOneField(db_column='AssetID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Models.asset')),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('assetid', models.OneToOneField(db_column='AssetID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Models.asset')),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('assetid', models.OneToOneField(db_column='AssetID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Models.asset')),
            ],
            options={
                'db_table': 'service',
                'managed': False,
            },
        ),
    ]
